(define (problem lost-stars-quest)
  (:domain la-conquista-delle-stelle-perdute)
  (:init
    (at-ship stella-errante zenthara-station)
    (engine-needs-repair stella-errante)
    (not (ship-has-resources stella-errante))
    (crystal-is-at crystal-of-jade jade-planet)
    (crystal-is-at crystal-of-fire fire-planet)
    (hazard-is-at sand-storms jade-planet)
    (hazard-is-at lava-creatures fire-planet)
    (hunter-is-unencountered)
    (not (is-allied-with-hunter))
    (vex-is-active)
    (vex-is-at desolate-planet)
    (planet-is-safe zenthara-station)
    (planet-is-safe desolate-planet)
    (path-is-known zenthara-station jade-planet)
    (path-is-known jade-planet zenthara-station)
    (path-is-known zenthara-station fire-planet)
    (path-is-known fire-planet zenthara-station)
    (nebula-path-is-known jade-planet desolate-planet)
    (path-is-known desolate-planet jade-planet)
  )
  (:goal (and
    (all-crystals-reunited)
    (vex-is-defeated)
    (power-is-awakened)
  ))
)